name: 'Terraform Setup'
#description: Run Terraform Plan and if successful, run Terraform Apply
#branding:
#  icon: filter
#  color: purple

jobs:
  tf-setup:
       
    ## Checkout the repository
    - name: Clone Repo ${GITHUB_REPOSITORY}
      uses: actions/checkout@v4

    ## Install and setup Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    ## Show Terraform version
    - name: Show Terraform Version
      run: terraform -chdir="${{ vars.TERRAFORM_WORKING_DIRECTORY }}" version
